language: go
sudo: false
go:
 - "1.13"
 - "1.14"
 - "1.15"
before_install:
 - go get github.com/mattn/goveralls
script:
 - go test -v -covermode=count -coverprofile=coverage.out 
 - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
